Jk 41
sagun03/react-shopping-ui-v2 pull request #8
Opened 2024-08-03 19:20 UTC by YugBandhara

2024-08-05 19:57 UTC, sagun03 requested changes

2024-08-05 19:57 UTC, sagun03 commented on src/App.jsx
> +                  // <Suspense
remove this cooment

2024-08-05 19:57 UTC, sagun03 commented on node-shopping-server.code-workspace
> +{
remove this sd this in gitignore

2024-08-05 19:57 UTC, sagun03 commented on src/components/ProductRangeCard.jsx
> +        Quantity: 1,
why Quantity not quantity?
pplease use naming convention

2024-08-05 19:57 UTC, sagun03 commented on src/components/ProductRangeCard.jsx
> +      window.location.reload();
why reloading the page??

2024-08-05 19:57 UTC, sagun03 commented on src/hooks/useCart.jsx
> +      window.location.reload();
why reloading?

2024-08-05 19:57 UTC, sagun03 commented on src/hooks/useCart.jsx
> +      window.location.reload();
why reloading

2024-08-05 19:57 UTC, sagun03 commented on src/pages/Cart.jsx
> +                            Rs. {item?.productDetails?.sizes[0]?.price * item?.quantity}
why only sizes[0] what about other sizes object?

2024-08-05 19:57 UTC, sagun03 commented on src/pages/Home.jsx
> +import React from "react";
remove this compoent

2024-08-05 19:57 UTC, sagun03 commented on src/services/cartService.js
> +      }
can't we optimise it, it beig used in every function, too much redunant thing can we move this inside api.Client and just paas the method nd data from here?

2024-08-05 19:57 UTC, sagun03 commented on src/hooks/useCart.jsx
> +      window.location.reload();
invalidateQuery

2024-08-05 20:04 UTC, YugBandhara commented on src/pages/Cart.jsx
> +                            Rs. {item?.productDetails?.sizes[0]?.price * item?.quantity}
This is beacuse I am extracting the aztudal size like 250 ml por 500ml which is added to cart , and I am only sending one object in array of selected size

2024-08-06 00:16 UTC, sagun03 approved these changes

2024-08-06 00:17 UTC, merged